version: 0.1.{build}

environment:
  PYTHON: "C:\\Python36-x64"
  CONDA: "C:\\Miniconda36-x64"

install:
- cmd: set PATH=%CONDA%;%CONDA%/Scripts;%CONDA%/Library/bin;%PATH%
- pip install pynsist
- conda env update
test_script:
- cmd: activate MultiColoc
- cmd: pytest --junitxml ./unittests.xml
- ps: $wc = New-Object 'System.Net.WebClient'
- ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))

build_script:
- cmd: pynsist install.cfg

artifacts:
- path: /build/nsis/MultiColoc*.exe
  name: Installer